@hostname = https://next-route-handler-revalidation.preview.dundle.dev

@contentType = application/json

@country = au


###
GET {{hostname}}/api/category/{{country}} HTTP/1.1
Content-Type: {{contentType}}
