@hostname = https://next-route-handler-revalidation.preview.dundle.dev

@contentType = application/json

@country = au


###
GET {{hostname}}/api/time HTTP/1.1
Content-Type: {{contentType}}

GET {{hostname}}/api/time-cached HTTP/1.1
Content-Type: {{contentType}}
